### ISSUE TITLE
Implement analog clock

### ISSUE THREAD

**Issue by ScottChapman** [merky1/PiClock#10]
I think this should be relatively easy; seen a lot of implementations out there. I'm not much of a UX guy, so not sure I could really help here...

**Comment by merky1** [comment]
Agree, it's on the list of things to do, and now documented ;)

**Comment by merky1** [comment]
![analog-clock](https://user-images.githubusercontent.com/8691286/42409541-9fb8e2dc-81a9-11e8-958d-3ba31ecaac5d.png)

Clock is stable - closing issue.
