### ISSUE TITLE
Analog clock face ignores fontcolor

### ISSUE THREAD

**Issue by merky1** [merky1/PiClock#20]
![analog](https://user-images.githubusercontent.com/8691286/45779283-9dfb3580-bc28-11e8-8ac9-8208bda29d55.png)

I have the hands updating, but I use an SVG for the clock face, and I think that will not work for color selection.  I am not that good at building graphics and transitions, so tabling this for someone else to look at.

**Comment by ScottChapman** [comment]
What's the issue? The clock numbers on the face?

**Comment by merky1** [comment]
It was, so I tested another mechanism, and things look worse.  The svg I used for this version did not adjust for color.

Going to revert and figure something out for the numbers.

**Comment by ScottChapman** [comment]
I think there are some good example of HTML/CSS analog clocks you could probably derive from. Probably have more control over things like fonts and colors?

**Comment by merky1** [comment]
Reverted code back to using the original clock model.  Need to replace the svg with fonts.

**Comment by merky1** [comment]
getting closer, but still not there : 
![image](https://user-images.githubusercontent.com/8691286/48303584-d48f5700-e4d9-11e8-8141-94bf6d022de7.png)

**Comment by merky1** [comment]
Problem fixed.  Still need to rotate clock face, but font color is respected.
