### ISSUE TITLE
Considered using one of the openweather node modules?

### ISSUE THREAD

**Issue by ScottChapman** [merky1/PiClock#21]
For example:
https://github.com/CICCIOSGAMINO/openweather-apis

**Comment by merky1** [comment]
By the time I thought about a module, I had enough of the open weather api encapsulated I focused on the weather.gov interfaces.  Not sure at this point the ow modules would give enough value to justify the time.  Basically, ow is a REST call, so it’s already pretty easy to pull apart.  Weather.gov was a ball of string that burned a lot of time.

**Comment by ScottChapman** [comment]
Gotcha.

It's sort of my first rule or writing code; don't write code! ;-)
