### ISSUE TITLE
Use darksky.net vs. Openweather

### ISSUE THREAD

**Issue by merky1** [merky1/PiClock#25]
basically, openweather seems very laggy and tends to be inaccurate for current conditions.  Darksky seems to update on a higher frequency level, but the API docs are ambiguous on how other users obtain API keys.

Will shoot an email to validate.

**Comment by merky1** [comment]
So I got an email back, and it sounds like it is acceptable to use developer accounts in PiClock the same way we have been using Openweather / google / etc.

"Thanks for checking. If I'm understanding correctly, this is fine!

Nowell Closser of The Dark Sky Company, LLC"

**Comment by merky1** [comment]
Need to give it a few days, but it seems the darksky api is clean enough to drop in.  You need to add you api key to the settings.json as : 

"dsAppId": "<API KEY>",

**Comment by rockman55** [comment]
Are you going to change your code to reflect the Darksky api?

**Comment by merky1** [comment]
Currently running with it.  Was going to add logic to switch between ds and openweather depending on user input.

**Comment by rockman55** [comment]
I vote for DarkSky. Have used some other projects using Openweather and sometimes get incorrect readings.

Thanks

**Comment by merky1** [comment]
If you take a current pull and add the dsAppId key to your settings, the code is live.  I may remove the us government weather pull for wind chill since ds does it.  I may stick with the usg forecast though, since I really like their icon set.

**Comment by rockman55** [comment]
Hello, 

I am having trouble running this project.

 

I have installed Stretch and run your instruction from PiClock/Install.md. I also copied the files from https://github.com/merky1/PiClock into my RPI into directory PiClock. Not sure where to go from there. Do you have any other instructions I am not seeing?

Thanks for your help. (I have been running the PiClock from Kevin Uhlir on Hackaday.IO, and want to get away from Weather Underground)

**Comment by merky1** [comment]
I'm closing this issue / feature, since darksky is working now.  I opened a new issue to work through your install issues @rockman55 #26
