### ISSUE TITLE
Lost maps

### ISSUE THREAD

**Issue by ScottChapman** [merky1/PiClock#27]
**Describe the bug**
All of a sudden I am not receiving maps. I am getting the radar images, just not the underlying maps

Had been working fine for a long time...

**Comment by merky1** [comment]
Working on mine fine.  Do you have a known working google key?  If your missing the underlying maps, it is most likely a google key issue.  You could also ctrl shift I to view the console from a desktop.

**Comment by ScottChapman** [comment]
I'll actually do the upgrade this weekend...
