### ISSUE TITLE
Help with configure

### ISSUE THREAD

**Issue by xxxDrewedxxx** [merky1/PiClock#36]
Please explain:
  "owAppId": "<yourID>",
  "dsAppId":"<your ID",
  "aerisID" : "<yourID>",
  "aerisSecret": "<yourSecret>",
  "ccAppId": "<yourID>",
Where would I find these. or what do they stand for?
OW ?  Open weather?
DS? Dark Sky?   
Areis?  
cc?
Are these all APIs, or my logins?

**Comment by merky1** [comment]
The app Id is something you get when signing up with a weather provider.

Currently the only valid providers are open weather, dark sky, and climacell.  Aeris decided to change their “free” policy, so the code currently ignores those settings.  If you look on the my account page for the various apis, they should have a string that represents your token / Id.

**Comment by merky1** [comment]
New install guide written by contributor.
