### ISSUE TITLE
I want to skin the interface somehow, can't figure out where to begin need some insight

### ISSUE THREAD

**Issue by TekMasterGaming** [merky1/PiClock#41]
I just installed this and got it working on my raspberry pi 3.  Its simply awesome.  But I would like to skin it and i can't figure out how to change it, its all blue and looks ok but i made it for my mom to be able to see it i will need to change the way it looks, where should i start?  I have extensive IT background but unfamiliar with electron and what js you did.  Just looking for insight.  Please contact me if you can redearthman@gmail.com

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by merky1** [comment]
You can put an image in the public directory and set the following properties:

"backgroundImg":"",
"imgFontColor":"",

Case sensitive name etc... Use any image that’s web ready (It uses the HTML background code)
Font Color is the hexadecimal RGB code.  “bef” is the PiClock default.  Otherwise, it cycles based on the temp, setting background and font colors based on temperature.

**Comment by TekMasterGaming** [comment]
thanks for the information, what should the image file name be or do i specify it in the settings? which file should i put the properties in and can you point me to the line of code or close to it that handles the cycling of the fonts and colors

**Comment by merky1** [comment]
It’s arbitrary, and the settings.json should be a copy of settings.example.  You should replace the keys with your info.

{"lat" : 0.0,
"lon" : 0.0,
"owAppId" : "your ow key here",
"dsAppId": "your dark sky key here",
"gMapKey" : "your google key here",
"aerisID" : "not used",
"aerisSecret": "not used",
"ccAppId" : "your climacell key here",
"curProvider" : "climacell", # valid options are nws | openweather | climacell
"currentConditionsInterval": 120,
"forecastInterval": 3600,
"clock":"digital",
"backgroundImg":"", #arbitrary filename of photo
"imgFontColor":"", #hex color code 
"mode":"local" #valid options are local | server | client - default PiClock is local 
}

**Comment by TekMasterGaming** [comment]
ah very good thank you i understand awesome app

**Comment by TekMasterGaming** [comment]
last two items i would like to ask, the digital clock, can it be changed to analog and when i click it it goes all black and white on me, why is that, and the transparency on the forecast buttons i would like to turn off

**Comment by merky1** [comment]
Set:
“clock”:”analog”

Keep in mind that I haven’t used analog, so there maybe all kinds of bugs.  I spent a weekend on this, and my skills as a UI developer are low.

Also you could suppress the “night mode” option by removing the contents of nightmode or take out the onClick on line 26 of index.html.

**Comment by TekMasterGaming** [comment]
excellent i will play around with it more and see what i can achieve, if i can add anything to it i will fork and upload
thanks for you help and support

**Comment by TekMasterGaming** [comment]
![2020-10-23 (3)](https://user-images.githubusercontent.com/14830490/97062510-3501ec80-1569-11eb-8be7-4adf36631093.png)


This is what it looks like so far, want to change the clock color if i can to match the main font color

**Comment by merky1** [comment]
I added the code to change the color in the repository.  Git pull to refresh.  I got the color to update, but the hands are using a different fill color?

![45F03AE9-D08E-4590-B2FE-BBC6D8020936](https://user-images.githubusercontent.com/8691286/97063582-85c81400-156e-11eb-8395-af80b114aa94.png)

**Comment by merky1** [comment]
I’ll look at this tomorrow.  Not an easy fix and my brains not catching the issue.

**Comment by merky1** [comment]
ok, fixed it... I didn’t test all the edges, but 
![835FDE5F-1859-4178-B69A-A9D12B5CA11E](https://user-images.githubusercontent.com/8691286/97066874-7f459680-1586-11eb-8814-47f16a9f493b.png)

**Comment by TekMasterGaming** [comment]
Most excellent thanks.  I will try it soon recompiling kernel atm.
