### ISSUE TITLE
forecast icons on right

### ISSUE THREAD

**Issue by TekMasterGaming** [merky1/PiClock#43]
would it be possible to replace the icons for different weather on the right for forecast and also when you click on them to replace those as well, i have been looking through your code and cannot figure out how to do it myself.  if you do not want to do such a modification please point me to location/line number i can begin with, i have the project in eclipse now but just basic editing is all i'm getting so far  and as i mentioned before the img background on the sub windows do not load i'd like to make the background app wide please and thank you and then i will leave you alone :-)

**Comment by merky1** [comment]
The forecast icons are pulled directly from the USG website in piclock js.js. Line 606 sets the icon.  You could switch the assignment to a function instead of my lazy pull.

**Comment by TekMasterGaming** [comment]
perfect thank you i will try that

**Comment by TekMasterGaming** [comment]
is is 664 in piclockjs.js???

	cur.curIcon = '<img id="curImg" src="'+ **observation.icon** +'&size=small"></img>';

**Comment by merky1** [comment]
606 is for the forecast.  664 is the current icon on the left.  The issue is I split the data and get current and forecast from two different sources.  You can use the parsecc sub as a primer, but the NWS uses different layouts for the data.  I never spent much time trying to map the icons since I liked the USG.

**Comment by TekMasterGaming** [comment]
i must be doing something wrong 606 on mine says  " function parseWgAlert(data) {  "

**Comment by TekMasterGaming** [comment]
i think you are talking about this line which is 695 in mine weird

	cur.curIcon = desc.icon;

**Comment by TekMasterGaming** [comment]
i'm thinking of using these icons https://github.com/ClimaCell-API/weather-code-icons/tree/master/color

**Comment by TekMasterGaming** [comment]
i'm using climacell in settings.json and should translate easy if i can make heads/tails of this thanks for your help.

**Comment by TekMasterGaming** [comment]
ok i found the correct line after restoring from git

**Comment by TekMasterGaming** [comment]
i'm going to close this it would take to much work and nws icons are better description wise to be changing i guess i was just looking for a visual aspect for hard of seeing individuals with crisp svg icons because of the 7" screen i'm using, i will just get a bigger screen i think
