### ISSUE TITLE
Use Express & more modern JS

### ISSUE THREAD

**Issue by ScottChapman** [merky1/PiClock#7]
I think this project could be simplified greatly by using Express, and using more modern JS directives like `async/await`. Let me know if you would like me to show you...

**Comment by merky1** [comment]
Yeah, I do more ecma/rhino so if you have a better way to do things, go for it.  Right now I think I’m going to focus on moving the styles to css and eliminating chromium.  I had some hw issue that’s needed a new pi, so things stalled a little.  Now I’m back on it, so should make the css moves this weekend.

**Comment by ScottChapman** [comment]
I'm not much of a UI gui, so maybe I can help with the server side stuff...
